### Importing libraries

In [2]:
import numpy as np
import torch
import warnings
warnings.filterwarnings('ignore')

# <b> Hands-on with tensors </b>

First of all, we can create tensors naturally from Python lists:

In [3]:
A = [[6, 9, 2],
     [3, 3, 7],
     [1, 0, 3]]
     
A_tensor = torch.tensor(A)

This also works just as naturally with **Numpy ndArrays**:


In [4]:
B = np.array([0,1,2,3])
B_tensor = torch.from_numpy(B)

Just like in NumPy (and Tensorflow, for that matter), we can initialize tensors with random values, all ones, or all zeroes. Just provide the shape (and dtype if you want to specify the data type):

In [5]:
# with no dtype argument, torch will infer the type
C = torch.zeros(4,4) 

C

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Let’s not forget tensors don’t have to be 2-dimensional!

In [6]:
D = torch.ones(3,3,2, dtype=torch.int)

D

tensor([[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]], dtype=torch.int32)

A new tensor can be created from an existing one. So, if we wanted, we could create a new Tensor of zeros with the same properties (shape and data type) as the `A_tensor` we created:

In [7]:
A_tensor_zeros = torch.zeros_like(A_tensor)

A_tensor_zeros 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Or maybe we want random floating point values?

In [8]:
# the dtype argument allows you to explicitly specify the datatype of the tensor
A_tensor_rand = torch.rand_like(A_tensor, dtype=torch.float) 

A_tensor_rand

tensor([[0.5793, 0.0875, 0.4751],
        [0.0472, 0.2506, 0.8876],
        [0.5382, 0.4223, 0.0391]])

Want the attributes of a tensor?## Arba norite gauti tenzoriu atributus?

In [9]:
A_tensor_rand.dtype
# torch.float32

A_tensor_rand.shape
# torch.Size([3, 3])

A_tensor_rand.device

device(type='cpu')

# <b> Conclusion </b>
    
Creating tensors is fine, but the real fun starts when we can start manipulating them and applying mathematical operations. There are a ton of neat tensor operations already built-in, so we certainly won’t have time to go through them all. Instead, here is a link to check [them out in further detail](https://pytorch.org/docs/stable/torch.html), and just name a few:

- matrix multiplication
- compute eigenvectors and eigenvalues
- sorting
- index,slice,join
- hamming window 