1. What is PyTorch?

PyTorch is a depp learning framework that is popular for its ease of use and flexibility. It is used for both for both research and production purposes and has adopted by many companies

2. Can you explain why a GPU is preferred over CPU for deep learning applications?

A GPU is preferred ove  a CPU for deep learning applciations because it is able to process a large number of matrix operations very quickly. This is important for deep learning because it allows for faster training of the models.

3. How do you define a tensor in PyTorch?

A tensor is a multi-dimensional array used for numerical computation in PyTorch. Tensors can be created from Python lists or tuples using torch.Tensor() function.

4. What’s the difference between nn and nn.functional modules in PyTorch?

The nn module in PyTorch is for building neural networks, and the nn.funtional module contains a numebr of functionsn for working with neural networks. The main difference is that the nn module provides a higher-level API for working with neural networks while nn.funtional module provides more low-level functions.

5. When should we use CUDA or multi-processing with PyTorch?

CUDA is used for trainign on GPUs while multi-pre]ocessing is used for training on mulptiple CPU.

6. What are the advantages of using PyTorch over NumPy?

PyTorch is a deep learnign framework that is built on top of NumPy. It provides a higher level of abstraction than NumPy and can be used for tasks such as building neural netwroks and training models. PyTorch also supports CUDA that allows it run Oon GPUs for faster perfromance.

7. Create a random torch array of dimension 3 * 4

In [3]:
torch.randn(3,4)


tensor([[ 0.5212, -0.2051, -0.9753, -0.1608],
        [-0.9175, -1.1140,  1.5281, -1.3655],
        [-0.4171, -0.0542, -0.3036,  0.7887]])

8. View array x in 4 * 4 dimensions

x.view(4, 4)

9. Check the size of `a` torch tensor

a.size()

10. Convert from torch tensor to numpy

In [4]:
a = torch.randn(5, 4)
b = a.numpy()
b


array([[ 0.6128575 , -0.25903326, -0.20797499, -0.69383514],
       [-0.45672116, -0.09171169, -0.23421119, -1.3411856 ],
       [-1.9975188 ,  0.47887117,  2.1304028 , -0.04503021],
       [-0.5867677 ,  1.6330622 ,  0.93262964,  0.15035692],
       [-1.0494136 , -1.4439491 ,  0.11017434,  0.37217644]],
      dtype=float32)

11. Convert from numpy to torch tensor

In [5]:
c = torch.from_numpy(b)
c


tensor([[ 0.6129, -0.2590, -0.2080, -0.6938],
        [-0.4567, -0.0917, -0.2342, -1.3412],
        [-1.9975,  0.4789,  2.1304, -0.0450],
        [-0.5868,  1.6331,  0.9326,  0.1504],
        [-1.0494, -1.4439,  0.1102,  0.3722]])

12. Check if CUDA and GPU are available

In [7]:
torch.cuda.is_available()

False

13. Create a variable x in PyTorch, whose grad will be tracked

In [10]:
from torch.autograd import Variable

x = Variable(torch.Tensor([2]), requires_grad = True)
x


tensor([2.], requires_grad=True)

14. Create tensor with [2, 3], [4, 8]

In [13]:
torch.Tensor([[2, 3], [4, 8]])


tensor([[2., 3.],
        [4., 8.]])

15. Create a torch Variable using a

In [15]:
Variable(a, requires_grad = True)


tensor([[ 0.6129, -0.2590, -0.2080, -0.6938],
        [-0.4567, -0.0917, -0.2342, -1.3412],
        [-1.9975,  0.4789,  2.1304, -0.0450],
        [-0.5868,  1.6331,  0.9326,  0.1504],
        [-1.0494, -1.4439,  0.1102,  0.3722]], requires_grad=True)

16. Three steps of backward propagation

optimizer.zero_grad()

loss.backward()

optimizer.step()

17. Two ways to saving PyTorch models

torch.save(model, pathname)

torch.save(model.state_dict(), pathname)

18. Two ways to load PyTorch models

#### load the model

load_model = torch.load('model.path')

#### load the aprameters

model.load_state_dic(torch.load('model_state.path'))

19. Set default dtype of PyTorch to torch.float64

In [21]:
torch.set_default_dtype(torch.float64)


20. Write default type of nn.layers

In [22]:
torch.float32


torch.float32

21. Write matrix multiplication x with w

x.mm(w)

22. Use numpy data in PyTorch

1. Need to convert numpy data to Torch Tensor.
2. Need to convert Torch.Tensor to Variablebefore using it in the graph.

23. Concatenate torch tensors in a particular direction

torch.cat(, directions = 0 or 1)

24. Convert tensor size from 3 to (3, 1)

In [24]:
x = torch.tensor([3, 2, 1])
torch.unsqueeze(x, 1)


tensor([[3],
        [2],
        [1]])

25. What are the main differences between Tensorflow and PyTorch?

The main differences between TensorFlow and PyTorch are the following:

- TensorFlow is a more low-level library providing more flexibility for developers but also requiring more time and effort to really get the most of it. PyTorch, on the other hand, is much more intuitive and easy to use.
- TensorFlow also supports better the distributed training while PyTorch is better for research and experimentation due to its speed in dynamic computational graph.