1. What is TensorFlow?

TensorFlow is an open source platform for machine learning that allows developers to create, train, test, and deploy machine learning modles, including several types of neural networks. It works with Python, Java and C++ and can be also in teh browser and mile applications.

2. What is a tensor?

A tensor is immutable, multi-dimensional arrays with uniform type. They are similar to NumPy arrays.

3. What is the rank of a tensor?

The rank of tensor is the number of idneces required to select and individual element of the tensor. You can think about it as the number dimensions.

4. What is a `rank-0` tensor?

A `rank-0` tensor is one with a single value and noa axes.

5. How would you implement a `rank-0` tensor in Python?

In [3]:
rank_0_tensor = tf.constant(52)
print(rank_0_tensor)

tf.Tensor(52, shape=(), dtype=int32)


6. What is a `rank-1` tensor?

A `rank-1` tensor is like a list of values. It has one axis or dimenion.

7. What is another name for a `rank-1` tensor?


A `rank-1` tensor is also called a `vector`.

8. How would you implement a `rank-1` tensor in Python?

In [4]:
rank_1_tensor = tf.constant([14, 1, -1])
print(rank_1_tensor)

tf.Tensor([14  1 -1], shape=(3,), dtype=int32)


9. What is a `rank-2` tensor?

A `rank-2` tensor is a tensor with two dimensions or axes. You can think of this as a two-dimenional array or a table of values.

10. What is another name for a `rank-2` tensor?

A `rank-2` tensor is commonly referred to as a matrix.

11. How would you implement a `rank-2` tensor in Python?

In [6]:
rank_2_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


12. What does the shape of a tensor signify?

A tensor's shape is the number of elements in each of its dimensions, For example, a tensor with 2 rows and 3 columns has shape [2, 3].

13. How can you determine the number of axes of a tensor in TensorFlow?

We can use the tensor's ndim attribute to output the number of dimensions.


In [7]:
print(rank_2_tensor.ndim)

2


14. What is the size of a tensor?

The size of a tensor is the total number of items it contains. This can be calculated by multiplying each element in teh tensor's shape vector.

15. How do you calculate the size of a tensor in TensorFlow?

TensorFlow provides `size()` method that can be used follows:


In [8]:
print(int(tf.size(rank_2_tensor)))

9


16. How do you convert a tensor to a NumPy array?

There are two methods. We can use `np.array` and `tensor.numpy`.

In [9]:
import numpy as np
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [10]:
rank_2_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

17. How to convert Numpy array to TensorFlow tensor?

tf.convert_to_tensor()

18. How do you add tensors?

We can add with `tf.add` and `+` operator.

In [11]:
print(tf.add(rank_2_tensor, rank_2_tensor))

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)


In [12]:
print(rank_2_tensor + rank_2_tensor)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)


19. How do you perform element-wise multiplication on tensors?

We can use `tf.multiply` method or `*`.

In [21]:
print(tf.multiply(rank_1_tensor, rank_1_tensor))

tf.Tensor([196   1   1], shape=(3,), dtype=int32)


In [22]:
print(rank_1_tensor * rank_1_tensor)

tf.Tensor([196   1   1], shape=(3,), dtype=int32)


20. How do you multiply matrices in TensorFlow?

we can multiply matrices by using `tf.matmul` or `@` operator.

In [23]:
print(tf.matmul(rank_2_tensor, rank_2_tensor))

tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)


In [24]:
print(rank_2_tensor @ rank_2_tensor)

tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)


21. What is eager execution in TensorFlow?

Execute opertaions immediately.

22. How to get the TensorFlow version?

In [25]:
tf.version.VERSION

'2.10.0'

23. What is TensorBoard?


Vizualisation tool for TensorFlow.

24. What is the backend of TensorFlow?

Keras

25. Why Tensorflow uses computational
graphs?

Calculations can be done in parallel.